- name: Deploy app on EC2
  run: |
    ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
      cd /home/ec2-user/docker-app
      sudo systemctl stop httpd || true
      sudo systemctl disable httpd || true
      docker stop myapp-container || true
      docker rm myapp-container || true
      docker stop $(docker ps -q) || true
      docker rm $(docker ps -aq) || true
      docker build -t myapp .
      docker run -d --name myapp-container -p 80:80 myapp
    EOF
